### ISSUE TITLE
'alert(isPresented:content:)' will be deprecated in a future version of iOS

### ISSUE THREAD

**Issue by jamesrimmer** [kodecocodes/video-yfsa1-materials#1]
Hi there,

In the tutorial video for episode 12, SwiftUI State, Ray recommends using the alert method alert(isPresented:content:). I can see the video was made almost a year ago and it seems that since then this method has planned to be deprecated. Xcode recommends using a different method called alert(title:isPresented:Presenting::actions:) instead. Still being relatively novice at coding and Swift, I'm not sure how to take the information from the tutorial video and put it into this other method instead. Would it be possible to just update this particular episode to use the new method?

Many thanks

James

**Comment by jellodiil** [comment]
Hey James, 
An update for this course is in happening right now,  and should be coming out soon, and we have paid special attention to this episode.
You are quite right that the  alert method has changed. Instead of what Ray is typing on screen, your code should look like this:

```swift
        .alert(
          "Hello there!",
          isPresented: $alertIsVisible,
          presenting: {
            let roundedValue = Int(sliderValue.rounded())
            return (
              roundedValue,
              game.points(sliderValue: roundedValue)
            )
          } () as (roundedValue: Int, points: Int)
        ) { data in
          Button("Awesome!") {
            game.startNewRound(points: data.points)
          }
        } message: { data in
          Text("The slider's value is \(data.roundedValue).\n" + "You scored \(data.points) points this round.")
        }
 ```

Hope this helps! If not, until the update comes out with a bit more explanation, I suggest reaching out in the [forums](https://forums.raywenderlich.com/) or in [RW Chat on discord](https://discord.com/invite/ZTUmDxX).
